source 'https://rubygems.org'

#RailsCasts #415

gem 'rails', '4.0.0.rc2'
gem 'sqlite3'

gem 'sass-rails',   '~> 4.0.0.rc1'
gem 'coffee-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'

#helping with transition
gem 'protected_attributes'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'