source 'https://rubygems.org'


gem 'rails', '4.0.0.rc2'


group :development, :test do
	gem 'sqlite3', '1.3.7'
	gem 'rspec-rails', 	'2.13.1'
end

gem 'sass-rails',   '4.0.0.rc1'
gem 'uglifier', 	'2.1.1'
gem 'coffee-rails', '4.0.0'
gem 'jquery-rails', '2.2.1'

group :doc do
	gem 'sdoc', '0.3.20', require: false
end

group :production do
  gem 'pg', '0.15.1'
end

#helping with transition
gem 'protected_attributes'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'